[project]
name = "textual-serial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["ruff>=0.11.8"]

[tool.ruff.lint]
fixable = ["ALL"]
unfixable = []
